name: Generate Epic Matrix Snake

on:
  # Run automatically every 6 hours for more frequent updates
  schedule:
    - cron: "0 */6 * * *"
  
  # Allows manual trigger
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Generate the snake files with Matrix theme
      - name: Generate Epic Matrix Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AmazingMoaaz
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=00ff41&color_dots=c6e48b,7bc96f,239a3b,196127
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=00ff41&color_dots=161b22,0e4429,006d32,26a641,39d353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Push the generated files to the output branch
      - name: Deploy Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
